Repository BrunoZirnstein/kalender, pull requests merged in 2020-02, with the labels that each got.

#8 new/overview-grundgerüst
  event-overview.php
Labels: new

#9 new/database-init
  it_wintercamp20.sql
Labels: new

#19 new/display-events
  event-overview-styles.css
  event-overview.php
Labels: new

#28 fix/new-database
  event-detail.php
  itwc20.sql
Labels: bug

#29 fix/adding-general-styles
  event-detail.php
  event-overview.php
  styles.css
Labels: bug

#31 fix/klassen-anpassen
  event-detail.php
  event-overview.php
  styles.css
Labels: bug

#32 feat/ansprechpartner-email
  event-detail.php
Labels: feature

#33 new/teilnehmer-event
  event-detail-styles.css
  event-detail.php
Labels: new

#36 new/including-kalender
  event-detail.php
  event-overview.php
  general.css
  kalender.php
  mykalender.php
  navbar.css
  profil.php
  test.php
  test/profil.php
Labels: new

#37 fix/farben-kalender
  packages/core/main.css
  profil.php
Labels: bug

#38 new/event-form
  event-overview-styles.css
  event-overview.php
  event_form.php
  general.css
Labels: new

#39 feat/link-user-profile
  event-detail.php
Labels: feature

#40 feat/teilnehmer-anzahl
  event-overview-styles.css
  event-overview.php
  profil.php
Labels: feature

#41 feat/add-teilnehmen-funktion
  event-overview.php
  teilnehmen.php
Labels: feature

#42 fix/overview-verbessert
  event-detail.php
  event-overview-styles.css
  profil.php
Labels: feature

#43 fix/link-post
  event-detail.php
Labels: bug

#44 feat/colored-events
  event-overview-styles.css
  event-overview.php
Labels: feature

#45 feat/event-kalender
  event-kalender.php
Labels: feature

#46 new/azubi-kalender
  azubi-kalender.php
Labels: new

#47 fix/teilnehmen-verbessern
  event-overview.php
  teilnehmen.php
Labels: bug

#48 feat/ansprechpartner-profil-link
  event-detail.php
Labels: feature

#49 fix/farben-event-kalender
  event-kalender.php
Labels: bug
